name: Build and Publish
on:
    release:
        types:
            - "created"

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Install Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 16.x
            - name: Install Dependencies
              run: npm install
            - name: Publish
              if: success() && startsWith(github.ref, 'refs/tags/')
              run: npm run deploy
              env:
                  VSCE_PAT: ${{ secrets.VSCE_PAT }}
